server:
  port: 8897
      
---
  
spring:
  config:
    activate:
      on-profile: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/testjpa?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#    username: oneinvest
#    password: oneinvest123
#  jpa:
#    show-sql: true
#    hibernate:
#       ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:oneinvestdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

oneInvest:
  security:
    jwt:
      secret: testSecretKey
      expirationInMs: 600000
      refreshExpirationInMs: 900000

---
  
spring:
  config:
    activate:
      on-profile: test

---

spring:
  config:
    activate:
      on-profile: prod
